# Generated by Django 4.1.7 on 2023-03-22 10:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, null=True)),
                (
                    "column_separator",
                    models.CharField(
                        choices=[
                            (",", "Comma ( , )"),
                            (";", "Semicolon ( ; )"),
                            ("|", "Pipe ( | )"),
                        ],
                        default=",",
                        max_length=1,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column_name",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Column name"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("FN", "Fullname"),
                            ("EM", "Email"),
                            ("BR", "Birthdate"),
                            ("DM", "Domain"),
                            ("AD", "Address"),
                            ("PN", "Phone number"),
                            ("AG", "Age"),
                            ("TX", "Text"),
                        ],
                        default="FN",
                        max_length=2,
                    ),
                ),
                (
                    "ORDER",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0)
                        ],
                    ),
                ),
                (
                    "range_from",
                    models.IntegerField(blank=True, null=True, verbose_name="From"),
                ),
                (
                    "range_to",
                    models.IntegerField(blank=True, null=True, verbose_name="To"),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_type",
                        to="schemas.schema",
                    ),
                ),
            ],
        ),
    ]
